dailyfresh/apps/cart/urls.py
from django.conf.urls import url

from cart import views

urlpatterns = [
    # url(r'^register/$', views.register)
    url(r'^add/$', views.AddCartView.as_view(), name='add'),
    url(r'^$', views.CartInfoView.as_view(), name='info'),
    url(r'^update/$', views.CartUpdateView.as_view(), name='update'),
    url(r'^delete/$', views.CartDeleteView.as_view(), name='delete'),
]

dailyfresh/apps/goods/urls.py
from django.conf.urls import url, include

from goods import views

urlpatterns = [
    # url(r'^register/$', views.register)
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<sku_id>\d+)$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)$', views.ListView.as_view(), name='list'),
]

dailyfresh/apps/orders/urls.py
from django.conf.urls import url

from orders import views

urlpatterns = [
    # url(r'^register/$', views.register)
    url(r'^place/$', views.PlaceOrderView.as_view(), name='place'),  # 订单详情页
    url(r'^commit/$', views.CommitOrderView.as_view(), name='commit'),  # 提交订单
    url(r'^(?P<page>\d+)/$', views.UserOrdersView.as_view(), name='info'),  # 所有订单页
    url(r'^pay/$', views.PayView.as_view(), name='pay'), # 支付请求
    url(r'^checkpay/$', views.CheckPayView.as_view(), name='checkpay'), # 检查支付状态
    url('^comment/(?P<order_id>\d+)$', views.CommentView.as_view(), name="comment") # 评论详情页面
]

dailyfresh/apps/users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^active/(?P<token>.+)$', views.ActiveView.as_view(), name='active'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    # url(r'^$', views.index, name='index'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^address/$', views.AddressView.as_view(), name='address'),
    url(r'^info/$', views.InfoView.as_view(), name='info'),
    # url(r'^order/$', views.OrderView.as_view(), name='order'),
]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^$', include('goods.urls', namespace='goods')),
    url(r'^index/$', include('goods.urls', namespace='goods')),
    url(r'^search/', include('haystack.urls')),
]

dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/cart/views.py
import json

from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import View
from django_redis import get_redis_connection

from goods.models import GoodsSKU


class AddCartView(View):
    """
    点击添加购物车响应的视图，为post请求
    """

    def post(self, request):
        """
        添加购物车内容，是post请求
        1.通过request获取user, sku_id, count
        2.认证系统判读是否登录
        3.all()判断是否为空
        4.判断数值是否符合仓库内容
            4.1 判断sku_id是否存在
            4.2 判断count是否超出库存
            4.3 count应该不需要判断是否为整吧？？毕竟传不进来

        5.保存到redis
            5.1 先获取此商品id对应的值 hget()
            5.2 判断值是否为None，若不为None，则把当前count加上去
            5.3 保存 hset()

        6.从redis获取购物车商品总数，并用json返回
            6.1 hgetall()

        7.注意几个获取的数据都需要转码为int

        8.未登录状态添加到购物车
            8.1 通过cookie
                向浏览器中写入购物车cookie信息
                response.set_cookie('cart', cart_str)
                读取cookie中的购物车信息
                cart_json = request.COOKIES.get('cart')

        :param request: 请求对象
        :return: 返回json数据
        """
        print(111)
        # 1.
        # 通过request获取user, sku_id, count
        user = request.user
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        user_id = user.id
        print('user_id=', user_id)

        # 3.
        # all() 判断是否为空
        if not all((sku_id, count)):
            return JsonResponse({'code': 2, 'msg': '请求数据为空'})

        # 4.
        # 判断数值是否符合仓库内容
        # 4.1
        # 判断sku_id是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            print('sku不存在')
            return JsonResponse({'code': 3, 'msg': '请求的sku不存在'})

        # 4.3
        # count应该不需要判断是否为整吧？？毕竟传不进来,判断是否为数字
        try:
            count = int(count)
        except Exception as e:
            print(e)
            return JsonResponse({'code': 5, 'msg': '传入数值错误'})

        # 4.2
        # 判断count是否超出库存
        # stock = sku.get('stock')
        stock = sku.stock
        print('stock=', stock)
        if count > int(stock):
            print('超出库存')
            return JsonResponse({'code': 4, 'msg': '超出库存'})

        # 2.
        # 认证系统判读是否登录
        if not user.is_authenticated():
            # 未登录的情况
            # 1.
            # 先从cookie中，获取当前商品的购物车记录(cart_json)

            cart_json = request.COOKIES.get('cart')

            # 2.
            # 判断购物车(cart_json)
            # 数据是否存在，有可能用户从来没有操作过购物车
            if cart_json:
                # 2.1.如果(cart_json)存在就把它转成字典(cart_dict)
                cart_dict = json.loads(cart_json)
                # cart_dict = eval(cart_json)
            else:
                # 2.2.如果(cart_json)不存在就定义空字典(cart_dict)
                cart_dict = {}

            # 3.
            # 判断要添加的商品在购物车中是否存在
            try:
                origin_count = cart_dict.get(sku_id)
                count += origin_count
            except Exception as e:
                print(e)

            # 3.1.如果存在就取出源有值，并进行累加
            # 3.2.如果不存在就直接保存商品数量
            cart_dict[sku_id] = count

            # 4.
            # 将(cart_dict)
            # 重新生成json字符串，方便写入到cookie
            cart_json = json.dumps(cart_dict)
            # cart_json = str(cart_dict)
            # 7.
            # 计算购物车数量总和，方便前端展示
            cart_num = 0
            for val in cart_dict.values():
                cart_num += val

            # 5.
            # 创建JsonResponse对象，该对象就是要响应的对象
            response = JsonResponse({'code': 0, 'msg': '添加到购物车成功', 'cart_num': cart_num})

            # 6.
            # 在响应前，设置cookie信息
            response.set_cookie('cart', cart_json)

            return response
            # print('未登录，跳转到登录页面')
            # path = request.path
            # return JsonResponse({'code':1, 'msg':'未登录，跳转到登录页面', 'path':path})

        else:
            # 已登录的情况
            # 5.
            # 保存到redis   cart_user_id : sku_id1 count1 sku_id2 count2....

            print(111)
            redis_conn = get_redis_connection('default')
            # print(222)
            # 5.1
            # 先获取此商品id对应的值
            # hget()
            ret_num = redis_conn.hget('cart_%s' % user.id, sku_id)

            print('ret_num=', ret_num)

            # 5.2
            # 判断值是否为None，若不为None，则把当前count加上去
            if not ret_num:
                ret_num = 0
            count += int(ret_num)

            print('count=', count)
            # 5.3
            # 保存
            # hset()
            redis_conn.hset('cart_%s' % user.id, sku_id, count)

            # 6.
            # 从redis获取购物车商品总数，并用json返回
            # 6.1
            # hgetall()
            cart_num = 0
            cart_dict = redis_conn.hgetall('cart_%s' % user_id)
            print('cart_dict=', cart_dict)  # 若不存在，获取到的也是空字典
            print('type(cart_dict)=', type(cart_dict))
            # cart_dict2 = redis_conn.hgetall('cart_11')
            # print(cart_dict2)
            # if not cart_dict:
            #     cart_dict = {}

            for val in cart_dict.values():
                cart_num += int(val)

            print('cart_num=', cart_num)

            return JsonResponse({'code': 0, 'msg': '请求成功', 'cart_num': cart_num})


class CartInfoView(View):
    """购物车详情页面"""

    def get(self, request):
        """
        为什么是get？因为购物车详情页面不需要获取额外的数据，
        所有数据都可以从已保存的redis或cookie中获取
        1.获取sku的列表
        2.获取每种sku的数量
        3.获取每种sku的总价
        4.获取所有sku的数量
        5.获取所有sku的总价

        :param request:
        :return:
        """

        # < li class ="col01" > < input type="checkbox" name="" checked > < / li >
        # < li class ="col02" > < img src="images/goods/goods012.jpg" > < / li >
        # < li class ="col03" > 奇异果 < br > < em > 25.80元 / 500g < / em > < / li >
        # < li class ="col04" > 500g < / li >
        # < li class ="col05" > 25.80元 < / li >
        # < li class ="col06" >
        # < div class ="num_add" >
        # < a href = "javascript:;" class ="add fl" > + < / a >
        # < input type = "text" class ="num_show fl" value="1" >
        # < a href = "javascript:;" class ="minus fl" > - < / a >
        # < / div >< / li >
        # < li class ="col07" > 25.80元 < / li >
        # < li class ="col08" > < a href="javascript:;" > 删除 < / a > < / li >

        user = request.user
        # 1.获取sku对象列表 skus
        # 1.1 登不登陆两种情况获取
        if user.is_authenticated():
            # 已登录的情况
            redis_conn = get_redis_connection('default')
            cart_dict = redis_conn.hgetall('cart_%s' % user.id)  # 这是byte格式的,是cart字典
            # {b'1': b'7', b'2': b'7', b'3': b'1'}
            print(cart_dict)
            # cart_dict = cart_dict.encode()
            # print(cart_dict)
        else:
            # 未登录，从cookie中获取
            cart_json = request.COOKIES.get('cart')  # 获取的是json字符串
            print('cart_json=', cart_json)  # cart_json= {"1": 6, "3": 4}

            print(type(cart_json))
            if cart_json:
                cart_dict = json.loads(cart_json)
                # print(cart_dict)
            else:
                cart_dict = {}

        # 获取总数量 total_count
        # 获取总价格 total_amount
        skus = []
        total_count = 0
        total_amount = 0

        sku_str = GoodsSKU.objects.get(id='1')
        print('sku_str.id=',sku_str.id)
        sku_int = GoodsSKU.objects.get(id=1)
        print('sku_int.id=',sku_int.id)
        sku_byte = GoodsSKU.objects.get(id=b'1')
        print('sku_byte.id=',sku_byte.id)

        for sku_id, count in cart_dict.items():
            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                continue

            count = int(count)  # 强制转为int  每种sku的数量
            amount = sku.price * count  # 每种sku的总价

            # 添加到sku对象内
            sku.count = count
            sku.amount = amount
            # 获取总数量 total_count
            # 获取总价格 total_amount
            total_count += count
            total_amount += amount

            skus.append(sku)

        context = {
            'skus': skus,
            'total_amount': total_amount,
            'total_count': total_count
        }

        return render(request, 'cart.html', context)


class CartUpdateView(View):
    """购物车幂等性更新"""

    def post(self, request):
        """
        获取参数：sku_id, count
        校验参数all()
        判断商品是否存在
        判断count是否是整数
        判断库存
        判断用户是否登陆
        如果用户登陆，将修改的购物车数据存储到redis中
        如果用户未登陆，将修改的购物车数据存储到cookie中
        响应结果
        :param request:
        :return:
        """

        # 获取参数：sku_id, count
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        user = request.user
        # print(111)
        # try:
        # 校验参数all()
        if not all((sku_id, count)):
            return JsonResponse({'code': 1, 'message': '参数不全'})

        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'message': '商品不存在'})

        # 判断count是否是整数
        # 4.3
        # count应该不需要判断是否为整吧？？毕竟传不进来,判断是否为数字
        try:
            count = int(count)
        except Exception as e:
            print(e)
            return JsonResponse({'code': 5, 'msg': '传入数值错误'})

        # except Exception as e:
        #     print(e)

        # 4.2
        # 判断库存
        # 判断count是否超出库存
        # stock = sku.get('stock')
        stock = sku.stock
        print('stock=', stock)
        if count > int(stock):
            print('超出库存')
            return JsonResponse({'code': 4, 'message': '超出库存'})


            # 判断用户是否登陆
            # 2.
            # 认证系统判读是否登录
        if not user.is_authenticated():
            # 未登录的情况
            # 如果用户未登陆，将修改的购物车数据存储到cookie中
            # 1.
            # 先从cookie中，获取当前商品的购物车记录(cart_json)

            cart_json = request.COOKIES.get('cart')

dailyfresh/templates/detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-商品详情{% endblock %}

{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for category in categorys %}
                        <li><a href="{% url 'goods:list' category.id 1 %}"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="/">全部分类</a>
        <span>></span>
        <a href="{% url 'goods:list' sku.category.id 1 %}">{{ sku.category.name }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>

        <form method="post" action="{% url 'orders:place' %}">   {# post表单，跳转到订单页面 #}
            {% csrf_token %}  {# csrf验证 #}
            <input type="hidden" name="sku_ids" value="{{ sku.id }}">
            {# 隐藏提交sku_id的input,注意，为了跟从购物车过去的保持一致，所以name也改成sku_ids #}

            <div class="goods_detail_list fr">
                <h3>{{ sku.name }}</h3>
                <p>{{ sku.title }}</p>
                <div class="prize_bar">
                    <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                    <span class="show_unit">单  位：{{ sku.unit }}</span>
                </div>
                {% if other_skus %}
                    <div>
                        <p>其他规格:</p>
                        <ul>
                            {% for sku in other_skus %}
                                <li><a href="{% url 'goods:detail' sku.id %}">{{ sku.price }}元/{{ sku.unit }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="goods_num clearfix">
                    <div class="num_name fl">数 量：</div>
                    <div class="num_add fl">
                        <input type="text" class="num_show fl" id="num_show" name="count" value="1">   {# 商品数量 #}
                        <a href="javascript:;" class="add fr" id="add">+</a>
                        <a href="javascript:;" class="minus fr" id="minus">-</a>
                    </div>
                </div>
                <div class="total">总价：<em>{{ sku.price }}</em>元</div>
                <div class="operate_btn">
{#                    <a href="javascript:;" class="buy_btn" id="buy_btn">立即购买</a>#}
                    <input type="submit" class="buy_btn" id="buy_btn" value="立即购买">  {# 改为提交按钮 #}
                    <a href="javascript:;" class="add_cart" sku_id="{{ sku.id }}" id="add_cart">加入购物车</a>
                </div>
            </div>
        </form>

    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li id="tag_detail" class="active">商品介绍</li>
                <li id="tag_comment">评论</li>
            </ul>

            <div class="tab_content" id="tab_detail">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ sku.goods.desc|safe }}</dd>
                </dl>
            </div>

            <div class="tab_content" id="tab_comment" style="display: none;">
                {% for order in orders %}
                    <dl>
                        <dd>客户：{{ order.username }}&nbsp;&nbsp;&nbsp;时间：{{ order.ctime }}</dd>
                        <dt>{{ order.comment }}</dt>
                    </dl>
                    <hr/>
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}

{% block footer %}
    <div class="add_jump"></div>
{% endblock %}

{% block bottom_files %}
{#    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>#}
    <script type="text/javascript">
        $("#tag_detail").click(function () {
            $("#tag_comment").removeClass("active");
            $(this).addClass("active");
            $("#tab_comment").hide();
            $("#tab_detail").show();
        });

        $("#tag_comment").click(function () {
            $("#tag_detail").removeClass("active");
            $(this).addClass("active");
            $("#tab_detail").hide();
            $("#tab_comment").show();
        });

        $("#buy_btn").click(function () {
            var count = $("#num_show").val();
            window.location.href = '/order/commit?g={{goods.id}}@' + count;
        });

        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
        // 点击加入购物车
        $('#add_cart').click(function () {
            // 将商品的id 和 数量发送给后端视图，保存到购物车数据中
            var req_data = {
                sku_id: $('#add_cart').attr("sku_id"),
                count: $("#num_show").val(),
                csrfmiddlewaretoken: "{{ csrf_token }}"
            };
            {#            // 使用ajax向后端发送数据#}

            $.ajax({
                url: '/cart/add/',
                type: 'post',
                data: req_data,
                datatype: 'json'
            }).done(function (data) {
                {#                alert('ajax发送成功');#}
                var code = data.code;
                var msg = data.msg;
                var cart_num = data.cart_num;
                {#                alert(code, msg);#}
                if (code == 0) {
                    // 添加到购物车请求成功
{#                    alert(msg);#}
                    {#                    var show_count = $('#show_count')#}
                    $(".add_jump").stop().animate({
                            'left': $to_y + 7,
                            'top': $to_x + 7
                        },
                        "fast", function () {
                            $(".add_jump").fadeOut('fast', function () {
                                // 展示购物车总数量
                                $('#show_count').html(cart_num);
                            });
                        });

                } else if (code == 1) {
                    alert(msg);
                    var path = data.path;   // 这个path是添加购物车的path，没用啊
                    var currentUrl = location.href;  // 这个含有域名
                    alert(currentUrl);
                    location.href = '/users/login/?next=/goods/detail/{{ sku.id }}'; // 如果未登录，跳转到登录页面
                } else {
                    alert(msg);
                }

            }).fail(function () {
                alert('ajax请求失败')
            });


            {#            $.post("/cart/add", req_data, function (response_data) {#}
            {#                // 根据response_data中的code决定处理效果#}
            {#                if (1 == response_data.code) {#}
            {#                    // 用户未登录#}
            {#                    window.location.href = "/users/login";  // 让页面跳转到登录页面#}
            {#                } else if (0 == response_data.code) {#}
            {#                    // 添加到购物车成功#}
            {#                    $(".add_jump").stop().animate({#}
            {#                        'left': $to_y+7,#}
            {#                        'top': $to_x+7},#}
            {#                        "fast", function() {#}
            {#                            $(".add_jump").fadeOut('fast',function(){#}
            {#                                $('#show_count').html(response_data.cart_num);#}
            {#                            });#}
            {#                    });#}
            {##}
            {#                } else {#}
            {#                    // 其他错误信息，alert展示#}
            {#                    alert(response_data.message);#}
            {#                }#}
            {#            }, "json");#}


        });
        $("#add").click(function () {
            var num_show = $("#num_show").val();
            num_show = parseInt(num_show)
            num_show += 1;
            $("#num_show").val(num_show);
            var price = $(".show_pirze>em").html()
            price = parseFloat(price);
            var total = price * num_show;
            $(".total>em").html(total.toFixed(2));
        });
        $("#minus").click(function () {
            var num_show = $("#num_show").val();
            num_show = parseInt(num_show)
            num_show -= 1;
            if (num_show < 1) {
                num_show = 1;
            }
            $("#num_show").val(num_show);
            var price = $(".show_pirze>em").html()
            price = parseFloat(price);
            var total = price * num_show;
            $(".total>em").html(total.toFixed(2));
        });
    </script>
{% endblock %}

dailyfresh/templates/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    天天生鲜-商品列表
{% endblock %}

{% block body %}

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for category in categorys %}
                        {# 默认跳转到某个分类商品列表的第一页 #}
                        <li><a href="{% url 'goods:list' category.id 1 %}"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="{% url 'goods:index' %}">全部分类</a>
        <span>></span>
        <a href="{% url 'goods:list' category.id 1 %}">{{ category.name }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for new_sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' new_sku.id %}"><img
                                    src="{{ new_sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="{% url 'goods:list' category.id 1 %}?sort=default"
                   {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=price"
                   {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=hot"
                   {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for sku in page_skus %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagenation">
                {% if page_skus.has_previous %}
                    <a href="{% url 'goods:list' category.id page_skus.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}

                {% for index in page_list %}
                    <a href="{% url 'goods:list' category.id index %}?sort={{ sort }}"
                       {% if index == page_skus.number %}class="active"{% endif %}>{{ index }}</a>
                {% endfor %}

                {% if page_skus.has_next %}
                    <a href="{% url 'goods:list' category.id page_skus.next_page_number %}?sort={{ sort }}">下一页</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

dailyfresh/templates/order_comment.html
{% extends 'user_center_base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-用户中心{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'users:info' %}">· 个人信息</a></li>
                <li><a href="{% url 'orders:info' 1 %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'users:address' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">订单评价</h3>
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
                <li class="col02 stress">{{ order.status_name }}</li>
            </ul>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{ order.order_id }}">
                <input type="hidden" name="total_count" value="{{ order.skus|length }}">
                {% for sku in order.skus %}
                    <table class="order_list_table w980">
                        <tbody>
                        <tr>
                            <td width="80%">
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ sku.default_image.url }}"></li>
                                    <li class="col02">{{ sku.name }}<em>{{ sku.price }}/{{ sku.unit }}</em></li>
                                    <li class="col03">{{ sku.count }}</li>
                                </ul>
                            </td>
                            <td width="20%">{{ sku.amount }}元</td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="site_con">
                        <input type="hidden" name="sku_{{ forloop.counter }}" value="{{ sku.id }}">
                        <div class="form_group form_group2">
                            <label>评价内容：</label>
                            <textarea class="site_area" name="content_{{ forloop.counter }}"></textarea>
                        </div>
                    </div>
                {% endfor %}
                <input type="submit" name="" value="提交" class="info_submit">
            </form>
        </div>
    </div>
{% endblock %}